package SEMIFINALS.BankAccountSystem;
import java.util.HashMap;
import java.time.Year;

//this class stores all created Bank Accounts
public class BankDataBase {
    private HashMap<Integer, BankAccount> listOfAccounts;
    
    public BankDataBase(){
        this.listOfAccounts = new HashMap<>();
    }

    //methods
    public BankAccount createAndAddAccount(String name, double balance){
        int accountNumber = generateAccountNumber();
        BankAccount b = new BankAccount(accountNumber, name, balance);
        listOfAccounts.put(accountNumber, b);
        System.out.println("\nSuccesfully created a bank account!");
        System.out.println("REMEMBER YOUR ACCOUNT NUMBER");
        System.out.println("--------------------------------------");
        System.out.println("Account number: " + accountNumber + " (generated by the bank)");
        System.out.println("Account Name: " + name);
        System.out.println("Initial Balance: $" + balance);
        System.out.println("--------------------------------------");
        return b;
    }

    public BankAccount geBankAccount(int accountNumber){
        if(accountExists(accountNumber)){
            return listOfAccounts.get(accountNumber);
        }
        else{
            return null;
        }
    }

    //helper methods
    private int generateAccountNumber(){
        Year currYear = Year.now();
        int accountNumber = currYear.getValue();
        accountNumber *= 1000;
        accountNumber += listOfAccounts.size();
        return accountNumber;
    }

    private boolean accountExists(int accountNumber){
        return listOfAccounts.containsKey(accountNumber);
    }

}
